// src/components/PanelsWrapper.tsx
import { FC } from 'react'

import Panel from '@/components/panel/Panel'
import { useConfigStore } from '@/store/ConfigStore.tsx'
import { PanelProvider } from '@/contexts/PanelContext.tsx'
import AddPanel from '@/components/panel/AddPanel.tsx'
const PanelsWrapper: FC = () => {
  const config = useConfigStore(state => state.config)

  return <div id="panels-wrapper" className="t-flex-1 t-flex t-h-full t-py-4 t-space-x-4 t-overflow-x-auto" data-cy="panels-wrapper">
    {
      (config.panels ?? [])
        .map((panelConfig, i: number) => (
          <PanelProvider panelConfig={panelConfig} index={i} key={i}>
            <Panel />
          </PanelProvider>
        ))
    }
    <AddPanel />
  </div>
}

export default PanelsWrapper

// src/components/panels/PanelsWrapper.vue
<template>
  <div class="panels-wrapper t-flex t-flex-col md:t-overflow-auto t-flex-1 md:t-flex-row md:t-space-x-4 t-space-y-4 md:t-space-y-0 t-px-4 lg:t-px-6 md:t-pb-4">
    <Panel
      v-for="(panel, i) in panels"
      v-show="panel.show"
      :key="`pc${i}`"
      :panel="panel"
      :active-view="getActiveView(i)"
      @active-view="onActiveViewChange($event, i)"
      class="t-flex-1 t-h-screen md:t-h-auto"
    />
  </div>
</template>

<script setup>

import { computed } from 'vue';
import { useConfigStore } from '@/stores/config';

import Panel from '@/components/panels/Panel.vue';

const configStore = useConfigStore();

const panels = computed(() => config.value.panels);
const config = computed(() => configStore.config);
const activeViews = computed(() => configStore.activeViews);

function onActiveViewChange(viewIndex, panelIndex) {
  configStore.setActivePanelView(viewIndex, panelIndex);
}

function getActiveView(panelIndex) {
  return activeViews.value[panelIndex];
}
</script>
