// src/components/metadata/ItemMetadata.tsx
import { FC, useState } from 'react'
import { usePanel } from '@/contexts/PanelContext.tsx'
import { useDataStore } from '@/store/DataStore.tsx'
import MetadataItem from '@/components/metadata/MetadataItem.tsx'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button.tsx'

const ItemMetadata: FC = () => {
  const { panelState } = usePanel()
  const { t } = useTranslation()
  const [showMetadata, setShowMetadata] = useState(false)

  const item = useDataStore(
    () => panelState && panelState.item ? panelState.item : null
  )


  const metadata = [
    { key: 'label', value: item?.n },
    { key: 'language', value: item?.lang?.join(',') },
    { key: 'image_license', value: item?.image?.license?.id },
    { key: 'image_notes', value: item?.image?.license?.notes },
  ].filter(i => i.value)


  return <div>
    <Button variant={'secondary'} title={t('please_click_to_view_metadata')} className="t-h-10 t-text-xl t-font-semibold t-mb-2 t-w-1/2 t-outline-none hover:t-bg-gray-200"
      onClick={() => setShowMetadata(!showMetadata)}>
      { t('item') }
    </Button>
    { showMetadata && <div className="item-metadata t-ml-4">
      {
        metadata.map((meta, i) => <MetadataItem item={meta} key={i} />)
      }
    </div>}
  </div>
}

export default ItemMetadata

// src/components/metadata/ItemMetadata.vue
<template>
  <div class="item-metadata t-mb-7">
    <h3 class="t-text-xl t-font-semibold t-mb-2">{{ $t(labels.item) }} {{ number }} / {{ total }}</h3>
    <div v-for="(meta, idx) in metadata" :key="idx" class="t-mb-4">
      <MetadataItem :item="meta"/>
    </div>
  </div>
</template>

<script setup lang="ts">

import { computed } from 'vue';
import { useStore } from 'vuex';
import MetadataItem from '@/components/metadata/MetadataItem.vue';

const store = useStore();

const item = computed<Item>(() => store.getters['contents/item']);
const itemUrl = computed<string>(() => store.getters['contents/itemUrl']);
const manifest = computed<Manifest>(() => store.getters['contents/manifest']);
const itemsCount = computed<number>(() => manifest.value?.sequence.length);
const labels = computed<Labels>(() => store.getters['config/config'].labels);
const number = computed<number>(() => (manifest.value ? manifest.value.sequence.findIndex(({ id }) => id === itemUrl.value) + 1 : 1));
const total = computed<number>(() => itemsCount.value ?? 1);
const metadata = computed(() => (
  [
    { key: 'label', value: item.value.n },
    { key: 'language', value: item.value?.lang?.join(',') },
    { key: 'image_license', value: item.value?.image?.license?.id },
    { key: 'image_notes', value: item.value?.image?.license?.notes },
  ].filter((item) => item.value)
));
</script>

<style scoped>

</style>
