// src/components/metadata/MetadataItem.tsx
import { FC } from 'react'
import { useTranslation } from 'react-i18next'
import MetadataValue from '@/components/metadata/MetadataValue.tsx'

interface MetadataItemProps {
  item: Metadata
}

const MetadataItem: FC<MetadataItemProps> = ({ item }) => {
  const { t } = useTranslation()

  return <div>
    <div>
      <h4 className="t-font-semibold t-text-sm t-text-gray-400">
        {t(item.key)}
      </h4>
      <MetadataValue value={item.value} />
    </div>
    <div className="nested-metadata t-ml-2">
      {
        item?.metadata?.map((meta, i) => <MetadataItem item={meta} key={i} />)
      }
    </div>
  </div>
}

export default MetadataItem

// src/components/metadata/MetadataItem.vue
<template>
  <div>
    <h4 v-if="!isLink()" class="t-font-semibold t-text-sm t-text-gray-400">
      {{ $t(label) }}
    </h4>
    <MetadataLink v-if="isLink()" :url="item.key" :text="item.value"/>
    <MetadataValue v-else :value="item.value" />
    <MetadataItem v-for="(childItem, idx) in childItems" :key="idx" :item="childItem" class="nested-metadata"/>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import MetadataLink from '@/components/metadata/MetadataLink.vue';
import MetadataValue from '@/components/metadata/MetadataValue.vue';

const props = defineProps<{
  item: Metadata,
}>();

const label = computed <string> (() => props.item?.key || 'other');
const childItems = computed(<Metadata> () => props.item?.metadata || []);

function isLink() : boolean {
  const regex = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#/%?=~_|!:,.;]*[-A-Z0-9+&@#/%=~_|])/ig;
  const matches = (typeof props.item?.key === 'string') ? props.item?.key?.match(regex) : null;

  return matches !== null;
}

</script>

<style scoped>

.nested-metadata {
  margin-left: 8px;
  margin-top: 2.5px;
}

</style>
